In [36]:
import numpy as np
from numpy import linalg as LA

In [8]:
A = np.array([[1, 2, 3], [2, 7 ,4]])
B = np.array([[1, -1], [0, 1]])
C = np.array([[5, -1], [9, 1], [6, 0]])
D = np.array([[3, -2, -1], [1, 2, 3]])
u = np.array([[6, 2, -3, 5]])
v = np.array([[3, 5, -1, 4]])
w = np.array([[1], [8], [0], [5]])

In [14]:
#Q1
print('Dimension of A is: %s by %s' % (A.shape[0], A.shape[1]))
print('Dimension of B is: %s by %s' % (B.shape[0], B.shape[1]))
print('Dimension of C is: %s by %s' % (C.shape[0], C.shape[1]))
print('Dimension of D is: %s by %s' % (D.shape[0], D.shape[1]))
print('Dimension of u is: %s by %s' % (u.shape[0], u.shape[1]))
print('Dimension of v is: %s by %s' % (v.shape[0], v.shape[1]))
print('Dimension of w is: %s by %s' % (w.shape[0], w.shape[1]))

Dimension of A is: 2 by 3
Dimension of B is: 2 by 2
Dimension of C is: 3 by 2
Dimension of D is: 2 by 3
Dimension of u is: 1 by 4
Dimension of v is: 1 by 4
Dimension of w is: 4 by 1


In [37]:
#Q2
print('u+v is:', sum(u, v))
print('u-v is:', u - v)
print('alpha*u is:', 6 * u)
print('u*v is:', u * v)
print('unit vector u is:', LA.norm(u))

u+v is: [[ 9  7 -4  9]]
u-v is: [[ 3 -3 -2  1]]
alpha*u is: [[ 36  12 -18  30]]
u*v is: [[18 10  3 20]]
unit vector u is: 8.60232526704


In [42]:
#Q3
print('A + C is not defined.')
print('A - C^T is: ', A - C.T)
print('C^T + 3D is:', C.T + 3*D)
print('B*A is:', np.dot(B, A))
print('B*A.T is not defined')

A + C is not defined.
A - C^T is:  [[-4 -7 -3]
 [ 3  6  4]]
C^T + 3D is: [[14  3  3]
 [ 2  7  9]]
B*A is: [[-1 -5 -1]
 [ 2  7  4]]
B*A.T is not defined


In [46]:
#Optional
print('B*C is not defined.')
print('C*B is:', np.dot(C, B))
print('B^4 is:', np.dot(B, np.dot(B, (np.dot(B, B)))))
print('A*A^T is:', np.dot(A, A.T))
print('D^T*D is:', np.dot(D.T, D))

B*C is not defined.
C*B is: [[ 5 -6]
 [ 9 -8]
 [ 6 -6]]
B^4 is: [[ 1 -4]
 [ 0  1]]
A*A^T is: [[14 28]
 [28 69]]
D^T*D is: [[10 -4  0]
 [-4  8  8]
 [ 0  8 10]]
